name: npm
on:
    push:
        branches: main

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
            - uses: ./
              name: Setup
              id: setup
              with:
                  build: npm run format && npm run test && npm run build
                  path: ./
            - uses: JS-DevTools/npm-publish@541aa6b21b4a1e9990c95a92c21adc16b35e9551 # v2.1.0
              with:
                  token: ${{ secrets.NPM_TOKEN }}
